// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: rpc_data_processing.proto

package pb_processing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataInfoTestResquest1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataTest string `protobuf:"bytes,1,opt,name=dataTest,proto3" json:"dataTest,omitempty"`
}

func (x *DataInfoTestResquest1) Reset() {
	*x = DataInfoTestResquest1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_processing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInfoTestResquest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfoTestResquest1) ProtoMessage() {}

func (x *DataInfoTestResquest1) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_processing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfoTestResquest1.ProtoReflect.Descriptor instead.
func (*DataInfoTestResquest1) Descriptor() ([]byte, []int) {
	return file_rpc_data_processing_proto_rawDescGZIP(), []int{0}
}

func (x *DataInfoTestResquest1) GetDataTest() string {
	if x != nil {
		return x.DataTest
	}
	return ""
}

type DataInfoTestRespone1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataResp string `protobuf:"bytes,1,opt,name=dataResp,proto3" json:"dataResp,omitempty"`
}

func (x *DataInfoTestRespone1) Reset() {
	*x = DataInfoTestRespone1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_processing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInfoTestRespone1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfoTestRespone1) ProtoMessage() {}

func (x *DataInfoTestRespone1) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_processing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfoTestRespone1.ProtoReflect.Descriptor instead.
func (*DataInfoTestRespone1) Descriptor() ([]byte, []int) {
	return file_rpc_data_processing_proto_rawDescGZIP(), []int{1}
}

func (x *DataInfoTestRespone1) GetDataResp() string {
	if x != nil {
		return x.DataResp
	}
	return ""
}

type ProcessingFileResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fileinfoprocess *FileInfoProcess `protobuf:"bytes,1,opt,name=fileinfoprocess,proto3" json:"fileinfoprocess,omitempty"`
}

func (x *ProcessingFileResquest) Reset() {
	*x = ProcessingFileResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_processing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessingFileResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingFileResquest) ProtoMessage() {}

func (x *ProcessingFileResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_processing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingFileResquest.ProtoReflect.Descriptor instead.
func (*ProcessingFileResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_processing_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingFileResquest) GetFileinfoprocess() *FileInfoProcess {
	if x != nil {
		return x.Fileinfoprocess
	}
	return nil
}

type ProcessingFileRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Noti string `protobuf:"bytes,1,opt,name=noti,proto3" json:"noti,omitempty"`
}

func (x *ProcessingFileRespone) Reset() {
	*x = ProcessingFileRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_processing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessingFileRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingFileRespone) ProtoMessage() {}

func (x *ProcessingFileRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_processing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingFileRespone.ProtoReflect.Descriptor instead.
func (*ProcessingFileRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_processing_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessingFileRespone) GetNoti() string {
	if x != nil {
		return x.Noti
	}
	return ""
}

var File_rpc_data_processing_proto protoreflect.FileDescriptor

var file_rpc_data_processing_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x62, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33,
	0x0a, 0x15, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54,
	0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22, 0x5f, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x45, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6e, 0x66,
	0x6f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2b, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x69, 0x42, 0x2f, 0x5a, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d,
	0x74, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_data_processing_proto_rawDescOnce sync.Once
	file_rpc_data_processing_proto_rawDescData = file_rpc_data_processing_proto_rawDesc
)

func file_rpc_data_processing_proto_rawDescGZIP() []byte {
	file_rpc_data_processing_proto_rawDescOnce.Do(func() {
		file_rpc_data_processing_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_data_processing_proto_rawDescData)
	})
	return file_rpc_data_processing_proto_rawDescData
}

var file_rpc_data_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_data_processing_proto_goTypes = []interface{}{
	(*DataInfoTestResquest1)(nil),  // 0: pb_storage.DataInfoTestResquest1
	(*DataInfoTestRespone1)(nil),   // 1: pb_storage.DataInfoTestRespone1
	(*ProcessingFileResquest)(nil), // 2: pb_storage.ProcessingFileResquest
	(*ProcessingFileRespone)(nil),  // 3: pb_storage.ProcessingFileRespone
	(*FileInfoProcess)(nil),        // 4: pb_storage.FileInfoProcess
}
var file_rpc_data_processing_proto_depIdxs = []int32{
	4, // 0: pb_storage.ProcessingFileResquest.fileinfoprocess:type_name -> pb_storage.FileInfoProcess
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_data_processing_proto_init() }
func file_rpc_data_processing_proto_init() {
	if File_rpc_data_processing_proto != nil {
		return
	}
	file_data_processing_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_data_processing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInfoTestResquest1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_processing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInfoTestRespone1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_processing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessingFileResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_processing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessingFileRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_data_processing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_data_processing_proto_goTypes,
		DependencyIndexes: file_rpc_data_processing_proto_depIdxs,
		MessageInfos:      file_rpc_data_processing_proto_msgTypes,
	}.Build()
	File_rpc_data_processing_proto = out.File
	file_rpc_data_processing_proto_rawDesc = nil
	file_rpc_data_processing_proto_goTypes = nil
	file_rpc_data_processing_proto_depIdxs = nil
}
