// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: rpc_data_storage.proto

package pb_storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataInfoTestResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataTest string `protobuf:"bytes,1,opt,name=dataTest,proto3" json:"dataTest,omitempty"`
}

func (x *DataInfoTestResquest) Reset() {
	*x = DataInfoTestResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInfoTestResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfoTestResquest) ProtoMessage() {}

func (x *DataInfoTestResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfoTestResquest.ProtoReflect.Descriptor instead.
func (*DataInfoTestResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{0}
}

func (x *DataInfoTestResquest) GetDataTest() string {
	if x != nil {
		return x.DataTest
	}
	return ""
}

type DataInfoTestRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataResp string `protobuf:"bytes,1,opt,name=dataResp,proto3" json:"dataResp,omitempty"`
}

func (x *DataInfoTestRespone) Reset() {
	*x = DataInfoTestRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataInfoTestRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfoTestRespone) ProtoMessage() {}

func (x *DataInfoTestRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfoTestRespone.ProtoReflect.Descriptor instead.
func (*DataInfoTestRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{1}
}

func (x *DataInfoTestRespone) GetDataResp() string {
	if x != nil {
		return x.DataResp
	}
	return ""
}

type FileInfoResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File   *FileInfo `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Iduser string    `protobuf:"bytes,2,opt,name=iduser,proto3" json:"iduser,omitempty"`
}

func (x *FileInfoResquest) Reset() {
	*x = FileInfoResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResquest) ProtoMessage() {}

func (x *FileInfoResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResquest.ProtoReflect.Descriptor instead.
func (*FileInfoResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfoResquest) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileInfoResquest) GetIduser() string {
	if x != nil {
		return x.Iduser
	}
	return ""
}

type FileInfoRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *FileInfoRespone) Reset() {
	*x = FileInfoRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRespone) ProtoMessage() {}

func (x *FileInfoRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRespone.ProtoReflect.Descriptor instead.
func (*FileInfoRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfoRespone) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type GetListFileUploadResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iduser string `protobuf:"bytes,1,opt,name=iduser,proto3" json:"iduser,omitempty"`
}

func (x *GetListFileUploadResquest) Reset() {
	*x = GetListFileUploadResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListFileUploadResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListFileUploadResquest) ProtoMessage() {}

func (x *GetListFileUploadResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListFileUploadResquest.ProtoReflect.Descriptor instead.
func (*GetListFileUploadResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetListFileUploadResquest) GetIduser() string {
	if x != nil {
		return x.Iduser
	}
	return ""
}

type GetListFileUploadRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fileinfo []*FileInfo `protobuf:"bytes,1,rep,name=fileinfo,proto3" json:"fileinfo,omitempty"`
}

func (x *GetListFileUploadRespone) Reset() {
	*x = GetListFileUploadRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListFileUploadRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListFileUploadRespone) ProtoMessage() {}

func (x *GetListFileUploadRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListFileUploadRespone.ProtoReflect.Descriptor instead.
func (*GetListFileUploadRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GetListFileUploadRespone) GetFileinfo() []*FileInfo {
	if x != nil {
		return x.Fileinfo
	}
	return nil
}

type DownloadFileResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFile string `protobuf:"bytes,1,opt,name=idFile,proto3" json:"idFile,omitempty"`
}

func (x *DownloadFileResquest) Reset() {
	*x = DownloadFileResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResquest) ProtoMessage() {}

func (x *DownloadFileResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResquest.ProtoReflect.Descriptor instead.
func (*DownloadFileResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadFileResquest) GetIdFile() string {
	if x != nil {
		return x.IdFile
	}
	return ""
}

type DownloadFileRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *DownloadFileRespone) Reset() {
	*x = DownloadFileRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRespone) ProtoMessage() {}

func (x *DownloadFileRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRespone.ProtoReflect.Descriptor instead.
func (*DownloadFileRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadFileRespone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadFileRespone) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UpdateStatusResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IdFile string `protobuf:"bytes,2,opt,name=idFile,proto3" json:"idFile,omitempty"`
}

func (x *UpdateStatusResquest) Reset() {
	*x = UpdateStatusResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResquest) ProtoMessage() {}

func (x *UpdateStatusResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResquest.ProtoReflect.Descriptor instead.
func (*UpdateStatusResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStatusResquest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateStatusResquest) GetIdFile() string {
	if x != nil {
		return x.IdFile
	}
	return ""
}

type UpdateStatusRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Noti string `protobuf:"bytes,1,opt,name=noti,proto3" json:"noti,omitempty"`
}

func (x *UpdateStatusRespone) Reset() {
	*x = UpdateStatusRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRespone) ProtoMessage() {}

func (x *UpdateStatusRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRespone.ProtoReflect.Descriptor instead.
func (*UpdateStatusRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_storage_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStatusRespone) GetNoti() string {
	if x != nil {
		return x.Noti
	}
	return ""
}

var File_rpc_data_storage_proto protoreflect.FileDescriptor

var file_rpc_data_storage_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x13,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x54, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x64, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x64, 0x75, 0x73, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x33, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x4c, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x30, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x22,
	0x2e, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x22,
	0x43, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x29, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x69, 0x42, 0x27, 0x5a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_data_storage_proto_rawDescOnce sync.Once
	file_rpc_data_storage_proto_rawDescData = file_rpc_data_storage_proto_rawDesc
)

func file_rpc_data_storage_proto_rawDescGZIP() []byte {
	file_rpc_data_storage_proto_rawDescOnce.Do(func() {
		file_rpc_data_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_data_storage_proto_rawDescData)
	})
	return file_rpc_data_storage_proto_rawDescData
}

var file_rpc_data_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_data_storage_proto_goTypes = []interface{}{
	(*DataInfoTestResquest)(nil),      // 0: pb_storage.DataInfoTestResquest
	(*DataInfoTestRespone)(nil),       // 1: pb_storage.DataInfoTestRespone
	(*FileInfoResquest)(nil),          // 2: pb_storage.FileInfoResquest
	(*FileInfoRespone)(nil),           // 3: pb_storage.FileInfoRespone
	(*GetListFileUploadResquest)(nil), // 4: pb_storage.GetListFileUploadResquest
	(*GetListFileUploadRespone)(nil),  // 5: pb_storage.GetListFileUploadRespone
	(*DownloadFileResquest)(nil),      // 6: pb_storage.DownloadFileResquest
	(*DownloadFileRespone)(nil),       // 7: pb_storage.DownloadFileRespone
	(*UpdateStatusResquest)(nil),      // 8: pb_storage.UpdateStatusResquest
	(*UpdateStatusRespone)(nil),       // 9: pb_storage.UpdateStatusRespone
	(*FileInfo)(nil),                  // 10: pb_storage.FileInfo
}
var file_rpc_data_storage_proto_depIdxs = []int32{
	10, // 0: pb_storage.FileInfoResquest.file:type_name -> pb_storage.FileInfo
	10, // 1: pb_storage.GetListFileUploadRespone.fileinfo:type_name -> pb_storage.FileInfo
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_data_storage_proto_init() }
func file_rpc_data_storage_proto_init() {
	if File_rpc_data_storage_proto != nil {
		return
	}
	file_data_storage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_data_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInfoTestResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataInfoTestRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfoResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfoRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListFileUploadResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListFileUploadRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_data_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_data_storage_proto_goTypes,
		DependencyIndexes: file_rpc_data_storage_proto_depIdxs,
		MessageInfos:      file_rpc_data_storage_proto_msgTypes,
	}.Build()
	File_rpc_data_storage_proto = out.File
	file_rpc_data_storage_proto_rawDesc = nil
	file_rpc_data_storage_proto_goTypes = nil
	file_rpc_data_storage_proto_depIdxs = nil
}
