// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: service_storage.proto

package pb_storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StogareClient is the client API for Stogare service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StogareClient interface {
	TestData(ctx context.Context, in *DataInfoTestResquest, opts ...grpc.CallOption) (*DataInfoTestRespone, error)
}

type stogareClient struct {
	cc grpc.ClientConnInterface
}

func NewStogareClient(cc grpc.ClientConnInterface) StogareClient {
	return &stogareClient{cc}
}

func (c *stogareClient) TestData(ctx context.Context, in *DataInfoTestResquest, opts ...grpc.CallOption) (*DataInfoTestRespone, error) {
	out := new(DataInfoTestRespone)
	err := c.cc.Invoke(ctx, "/pb_storage.Stogare/TestData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StogareServer is the server API for Stogare service.
// All implementations must embed UnimplementedStogareServer
// for forward compatibility
type StogareServer interface {
	TestData(context.Context, *DataInfoTestResquest) (*DataInfoTestRespone, error)
	mustEmbedUnimplementedStogareServer()
}

// UnimplementedStogareServer must be embedded to have forward compatible implementations.
type UnimplementedStogareServer struct {
}

func (UnimplementedStogareServer) TestData(context.Context, *DataInfoTestResquest) (*DataInfoTestRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestData not implemented")
}
func (UnimplementedStogareServer) mustEmbedUnimplementedStogareServer() {}

// UnsafeStogareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StogareServer will
// result in compilation errors.
type UnsafeStogareServer interface {
	mustEmbedUnimplementedStogareServer()
}

func RegisterStogareServer(s grpc.ServiceRegistrar, srv StogareServer) {
	s.RegisterService(&Stogare_ServiceDesc, srv)
}

func _Stogare_TestData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataInfoTestResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StogareServer).TestData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_storage.Stogare/TestData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StogareServer).TestData(ctx, req.(*DataInfoTestResquest))
	}
	return interceptor(ctx, in, info, handler)
}

// Stogare_ServiceDesc is the grpc.ServiceDesc for Stogare service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stogare_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_storage.Stogare",
	HandlerType: (*StogareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestData",
			Handler:    _Stogare_TestData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_storage.proto",
}
