// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: rpc_data_user.proto

package pb_authen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userinfo *UserInfo `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
}

func (x *UserResquest) Reset() {
	*x = UserResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResquest) ProtoMessage() {}

func (x *UserResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResquest.ProtoReflect.Descriptor instead.
func (*UserResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserResquest) GetUserinfo() *UserInfo {
	if x != nil {
		return x.Userinfo
	}
	return nil
}

type UserRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Noti string `protobuf:"bytes,1,opt,name=noti,proto3" json:"noti,omitempty"`
}

func (x *UserRespone) Reset() {
	*x = UserRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRespone) ProtoMessage() {}

func (x *UserRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRespone.ProtoReflect.Descriptor instead.
func (*UserRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserRespone) GetNoti() string {
	if x != nil {
		return x.Noti
	}
	return ""
}

type SignInResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userinfo *UserInfo `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
}

func (x *SignInResquest) Reset() {
	*x = SignInResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResquest) ProtoMessage() {}

func (x *SignInResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResquest.ProtoReflect.Descriptor instead.
func (*SignInResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_user_proto_rawDescGZIP(), []int{2}
}

func (x *SignInResquest) GetUserinfo() *UserInfo {
	if x != nil {
		return x.Userinfo
	}
	return nil
}

type SignInRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userinfo *UserInfo `protobuf:"bytes,1,opt,name=userinfo,proto3" json:"userinfo,omitempty"`
	Token    string    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SignInRespone) Reset() {
	*x = SignInRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRespone) ProtoMessage() {}

func (x *SignInRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRespone.ProtoReflect.Descriptor instead.
func (*SignInRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_user_proto_rawDescGZIP(), []int{3}
}

func (x *SignInRespone) GetUserinfo() *UserInfo {
	if x != nil {
		return x.Userinfo
	}
	return nil
}

func (x *SignInRespone) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenTokenResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthenTokenResquest) Reset() {
	*x = AuthenTokenResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenTokenResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenTokenResquest) ProtoMessage() {}

func (x *AuthenTokenResquest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenTokenResquest.ProtoReflect.Descriptor instead.
func (*AuthenTokenResquest) Descriptor() ([]byte, []int) {
	return file_rpc_data_user_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenTokenResquest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenTokenRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iduser string `protobuf:"bytes,1,opt,name=iduser,proto3" json:"iduser,omitempty"`
}

func (x *AuthenTokenRespone) Reset() {
	*x = AuthenTokenRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_data_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenTokenRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenTokenRespone) ProtoMessage() {}

func (x *AuthenTokenRespone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_data_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenTokenRespone.ProtoReflect.Descriptor instead.
func (*AuthenTokenRespone) Descriptor() ([]byte, []int) {
	return file_rpc_data_user_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenTokenRespone) GetIduser() string {
	if x != nil {
		return x.Iduser
	}
	return ""
}

var File_rpc_data_user_proto protoreflect.FileDescriptor

var file_rpc_data_user_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x62, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x21, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x69,
	0x22, 0x41, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x56, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a, 0x13, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2c, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x64, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x64, 0x75, 0x73, 0x65, 0x72, 0x42, 0x25, 0x5a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_data_user_proto_rawDescOnce sync.Once
	file_rpc_data_user_proto_rawDescData = file_rpc_data_user_proto_rawDesc
)

func file_rpc_data_user_proto_rawDescGZIP() []byte {
	file_rpc_data_user_proto_rawDescOnce.Do(func() {
		file_rpc_data_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_data_user_proto_rawDescData)
	})
	return file_rpc_data_user_proto_rawDescData
}

var file_rpc_data_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_data_user_proto_goTypes = []interface{}{
	(*UserResquest)(nil),        // 0: pb_authen.UserResquest
	(*UserRespone)(nil),         // 1: pb_authen.UserRespone
	(*SignInResquest)(nil),      // 2: pb_authen.SignInResquest
	(*SignInRespone)(nil),       // 3: pb_authen.SignInRespone
	(*AuthenTokenResquest)(nil), // 4: pb_authen.AuthenTokenResquest
	(*AuthenTokenRespone)(nil),  // 5: pb_authen.AuthenTokenRespone
	(*UserInfo)(nil),            // 6: pb_authen.UserInfo
}
var file_rpc_data_user_proto_depIdxs = []int32{
	6, // 0: pb_authen.UserResquest.userinfo:type_name -> pb_authen.UserInfo
	6, // 1: pb_authen.SignInResquest.userinfo:type_name -> pb_authen.UserInfo
	6, // 2: pb_authen.SignInRespone.userinfo:type_name -> pb_authen.UserInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_data_user_proto_init() }
func file_rpc_data_user_proto_init() {
	if File_rpc_data_user_proto != nil {
		return
	}
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_data_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenTokenResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_data_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenTokenRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_data_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_data_user_proto_goTypes,
		DependencyIndexes: file_rpc_data_user_proto_depIdxs,
		MessageInfos:      file_rpc_data_user_proto_msgTypes,
	}.Build()
	File_rpc_data_user_proto = out.File
	file_rpc_data_user_proto_rawDesc = nil
	file_rpc_data_user_proto_goTypes = nil
	file_rpc_data_user_proto_depIdxs = nil
}
