// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: service_authen.proto

package pb_authen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthenClient is the client API for Authen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenClient interface {
	SignUp(ctx context.Context, in *UserResquest, opts ...grpc.CallOption) (*UserRespone, error)
	SignIn(ctx context.Context, in *SignInResquest, opts ...grpc.CallOption) (*SignInRespone, error)
	AuthenToken(ctx context.Context, in *AuthenTokenResquest, opts ...grpc.CallOption) (*AuthenTokenRespone, error)
}

type authenClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenClient(cc grpc.ClientConnInterface) AuthenClient {
	return &authenClient{cc}
}

func (c *authenClient) SignUp(ctx context.Context, in *UserResquest, opts ...grpc.CallOption) (*UserRespone, error) {
	out := new(UserRespone)
	err := c.cc.Invoke(ctx, "/pb_authen.Authen/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenClient) SignIn(ctx context.Context, in *SignInResquest, opts ...grpc.CallOption) (*SignInRespone, error) {
	out := new(SignInRespone)
	err := c.cc.Invoke(ctx, "/pb_authen.Authen/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenClient) AuthenToken(ctx context.Context, in *AuthenTokenResquest, opts ...grpc.CallOption) (*AuthenTokenRespone, error) {
	out := new(AuthenTokenRespone)
	err := c.cc.Invoke(ctx, "/pb_authen.Authen/AuthenToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenServer is the server API for Authen service.
// All implementations must embed UnimplementedAuthenServer
// for forward compatibility
type AuthenServer interface {
	SignUp(context.Context, *UserResquest) (*UserRespone, error)
	SignIn(context.Context, *SignInResquest) (*SignInRespone, error)
	AuthenToken(context.Context, *AuthenTokenResquest) (*AuthenTokenRespone, error)
	mustEmbedUnimplementedAuthenServer()
}

// UnimplementedAuthenServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenServer struct {
}

func (UnimplementedAuthenServer) SignUp(context.Context, *UserResquest) (*UserRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedAuthenServer) SignIn(context.Context, *SignInResquest) (*SignInRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedAuthenServer) AuthenToken(context.Context, *AuthenTokenResquest) (*AuthenTokenRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenToken not implemented")
}
func (UnimplementedAuthenServer) mustEmbedUnimplementedAuthenServer() {}

// UnsafeAuthenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenServer will
// result in compilation errors.
type UnsafeAuthenServer interface {
	mustEmbedUnimplementedAuthenServer()
}

func RegisterAuthenServer(s grpc.ServiceRegistrar, srv AuthenServer) {
	s.RegisterService(&Authen_ServiceDesc, srv)
}

func _Authen_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_authen.Authen/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).SignUp(ctx, req.(*UserResquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authen_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_authen.Authen/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).SignIn(ctx, req.(*SignInResquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authen_AuthenToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenTokenResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).AuthenToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_authen.Authen/AuthenToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).AuthenToken(ctx, req.(*AuthenTokenResquest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authen_ServiceDesc is the grpc.ServiceDesc for Authen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_authen.Authen",
	HandlerType: (*AuthenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _Authen_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _Authen_SignIn_Handler,
		},
		{
			MethodName: "AuthenToken",
			Handler:    _Authen_AuthenToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_authen.proto",
}
